[project]
name = "ffdd"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/home/runner/workspace/ffdd/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Chainfolio-Digital-Asset-Portfolio-Manager]
path = "contracts/Chainfolio-Digital-Asset-Portfolio-Manager.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
